### ISSUE TITLE
Callbacks into Go

### ISSUE THREAD

**Issue by anacrolix** [petermattis/fastcgo#2]
I am calling C functions that call back into Go. Should that work with fastcgo?

**Comment by petermattis** [comment]
@anacrolix Probably not as the Go to C call switches to the system stack.

**Comment by anacrolix** [comment]
Okay cheers. Might be worth putting in the Readme and/or having a test?

**Comment by petermattis** [comment]
This package is something of a toy. Happy to merge a pull-request, but its not something I'm actively working on or using.
